### ISSUE TITLE
3x GUI issues. 2 i can replicate, 1 i haven't tried to test more than once so far.

### ISSUE THREAD

**Issue by wootriffic** [turtlecoin/turtle-wallet-electron#95] opened 2019-02-14 00:56 UTC
First issue: If you send/receive a transaction while in the wallet, then try to click on one of those transactions, you see a previous one rather than the one you're trying to click on.
so say i send 100 coins. if i click on it, i get another transactions details.
The way to fix that, close the wallet, open back up, and then you can, provided no other transactions happen by the time you've closed and opened it.

Second issue: if you search the pid, amount, or any other thing, you cant then go back to viewing all.
once again you have to close the wallet and open again.

Third issue: i can not replicate this one. I sent trtl to a wallet included the PID and it didn't include the PID when it sent. those coins went to their mega wallet but couldn't be put into my account. (tradesatoshi). I've since tested with Tradeogre with just 100 trtl and was fine. Not sure if i keep trying if it will do it or not. The send for TS doesn't show a pid  anywhere, but TO does.

I am from here fwd using the CLI rather than GUI.

**Comment by rixombea** [comment] 2019-02-14 03:35
@wootriffic thanks for reporting!

> First issue: If you send/receive a transaction while in the wallet, then try to click on one of those transactions, you see a previous one rather than the one you're trying to click on.
> so say i send 100 coins. if i click on it, i get another transactions details.
> The way to fix that, close the wallet, open back up, and then you can, provided no other transactions happen by the time you've closed and opened it.
> 
> Second issue: if you search the pid, amount, or any other thing, you cant then go back to viewing all.
> once again you have to close the wallet and open again.

I was able reproduce both of those reported ui glitch issue, fixed with commit: f6300fe

> Third issue: i can not replicate this one. I sent trtl to a wallet included the PID and it didn't include the PID when it sent. those coins went to their mega wallet but couldn't be put into my account. (tradesatoshi). I've since tested with Tradeogre with just 100 trtl and was fine. Not sure if i keep trying if it will do it or not. The send for TS doesn't show a pid anywhere, but TO does.

I tested many transactions with payment id, but unable to reproduce this one.
If you (or anyone else --> summoning @Sajo8 + @zpalmtree ) are able to reproduce this issue, please report the exact steps to reproduce it, because if this bug confirmed to be exists, it may have a fatal consequence.

Also, when you hit the "Send" button, you'll be presented with a confirmation dialog, with every detail about the transfer. That feature is there to help you verify that everything has been entered correctly.
So, always make sure to carefully verify everything before confirming to send your funds.

**Closed** 2019-02-15 08:11 UTC
Labels: help wanted, question
